name: rusty-argonone-snap # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Fan controller for the RPi4 Argon ONE case # 79 char long summary
description: |
  This is a community build of the rust implementation of the fan contrller
  for the Argon ONE case. The original

architectures:
  - build-on: armhf
    run-on: armhf
    
  - build-on: arm64
    run-on: arm64

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  argon-one-fan-controller:
    # See 'snapcraft plugins'
    plugin: rust
    source: https://github.com/jonlamb-gh/rpi4-argon-fan-controller.git

apps:
  argon-one-fan-controller:
    command: argon-fan-ctl -c $SNAP_DATA/config.toml
    plugs:
      - physical-memory-control

  daemon:
    command: argon-fan-ctl -config $SNAP_DATA/config/config.yaml
    daemon: simple
    plugs:
      - physical-memory-control
