#!/bin/sh -e

# Create a default config file
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
$SNAP/snap/command-chain/snapcraft-runner $SNAP/bin/argon-fan-ctl --write-defalut-config $SNAP_DATA/config.toml

exit 0
