#!/bin/sh -e

# Create a default config file
echo "# If set to true, please have 'step' set in your configuration file to use the
# feature to change fan speed according to temperature. If set to false, please
# have 'const_fan_speed' set in your configuration to set a constant fan speed.
dynamic = true
# As described above.
const_fan_speed = 0
# An array consists of pairs of temperature and fan_speed. When the detected
# temperature is greater than certain step but smaller than next step to that
# one, then that step will be used.
config = [
  { temperature = 40, fan_speed = 10  },
  { temperature = 50, fan_speed = 50  },
  { temperature = 60, fan_speed = 100 },
]
# The delay for the speed of the fan to change. Default to 30s if unset.
delay_on_change = 30" > $SNAP_DATA/argononed.conf

exit 0
